---
title: "Figure2_spxbiomass"
author: "meganedeziel"
date: "2024-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Package loading
```{r}
library("here")
library("tidyverse")
library("ggplot2")
#This script will produce Figure 2: The relative contribution of species to the average biomass on day 60 of the experiment
```

### Data importation
```{r}
Biom_data<-read.csv(here("data", "Relativebiomass_data.csv"), sep=";")
#info on data
#individual mass : in mg
#mean LA = mean leaf area : in mg
#mean SLA = mean specific leaf area : in mm2/mg
#initial relbiomass : in mg
#final relbiomass: in mg
```

### Plot
```{r}
#Mean biomass per species data
Plot_species<-Biom_data[Biom_data$Days==60,] %>%
  group_by(Mixture, Species) %>%
  mutate(mean_fin_relbiomass=mean(Final_relbiomass)) %>%
  mutate(standard_error=sd(Final_relbiomass)/sqrt(n())) %>%  #calculates standard error in biomass of each species composing the mixtures
  dplyr::select(., 3:5, 11, 12) %>%
  ungroup() %>%
  unique() 


Plot_species$Mixture<-fct_relevel(Plot_species$Mixture, c("Lm", "Sp", "Wc", "Lt", "LmSp", "LmWc", "LmLt", "SpWc", "SpLt", "WcLt", "LmSpWc", "LmSpLt", "SpWcLt", "LmWcLt", "LmSpWcLt"))

#Total biomass & standard error data
Errorbar_data_totalbiom<-Biom_data[Biom_data$Days==60,] %>%
  group_by(Block, Mixture) %>%
  mutate(tot_biomass_per_blockmix=sum(Final_relbiomass)) %>%
  ungroup() %>%
  dplyr::select(., 2, 3, 11) %>%
  unique() %>%
  group_by(Mixture) %>%
  mutate(mean_tot_biomass=mean(tot_biomass_per_blockmix)) %>%
  mutate(sd_tot_biomass=sd(tot_biomass_per_blockmix)/sqrt(n())) %>%
  dplyr::select(., 2, 4, 5) %>%
  unique() %>%
  ungroup

#Significance in net effect data
NE60$significance<-ifelse(NE60$NE>=1, "s", "ns")

Plotdat_fin<-merge(Plot_species, Errorbar_data_totalbiom, by="Mixture") %>%
  unique()

p<-ggplot(data=Plotdat_fin, aes(fill=Species, y=mean_fin_relbiomass, x=Mixture)) +
    geom_bar(position="stack", stat="identity", colour="black") +
    scale_fill_manual(values=alpha(c("#2D3184", "#32AAB5", "#B3E7C5", "#F3F1E4"), 0.7)) +
    theme_classic() +
    theme(text=element_text(size=15), axis.text.x = element_text(size = 13, angle = 60, hjust=1), panel.grid.major.y = element_line( size=.1, color="black")) +
    labs(x="Composition", y="Average biomass (mg)", pch=8) + 
    scale_y_continuous(limits=c(0, 3600), breaks=seq(0, 3600, by=400)) +
    geom_errorbar(aes(x=Mixture, ymin=mean_tot_biomass-sd_tot_biomass, ymax=mean_tot_biomass+sd_tot_biomass), width=0.4, colour="black", alpha=0.9, size=1.3) +
  # Add stars based on significance levels
  annotate(
    "text",
    x = c(7, 8, 9, 10, 12, 13, 14, 15),  # x-coordinates where stars should be placed
    y = c(3500, 3500, 3500, 3500, 3500, 3500, 3500, 3500),  # y-coordinate (adjust based on your plot)
    label = c("***", "**", "*", "*", "*", "*", "*", "8"),  # significance labels
    size = 5,  # adjust the size of the stars
    color = "red"  # color of the stars
  )
    geom_point(aes(x=Mixture, y=mean_tot_biomass), size=3) +
    geom_text(aes(label=ifelse()))
    guides(fill = guide_legend(override.aes = list(shape = NA)))  #removes the points in the legend


theme(text=element_text(size=15), plot.title=element_text(vjust=2)
```